namespace ReadExcelApp.Forms
{
    partial class CDRFormatForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CDRFormatForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel2 = new System.Windows.Forms.Panel();
            this.btnBTS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCustom = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTelenor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUfone = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnZong = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnWarid = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnJazz = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.gvFormatCDR = new System.Windows.Forms.DataGridView();
            this.lbSampleDownload = new System.Windows.Forms.LinkLabel();
            this.lbVideoLectureDownload = new System.Windows.Forms.LinkLabel();
            this.panel2.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gvFormatCDR)).BeginInit();
            this.SuspendLayout();
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.btnBTS);
            this.panel2.Controls.Add(this.btnCustom);
            this.panel2.Controls.Add(this.btnTelenor);
            this.panel2.Controls.Add(this.btnUfone);
            this.panel2.Controls.Add(this.btnZong);
            this.panel2.Controls.Add(this.btnWarid);
            this.panel2.Controls.Add(this.btnJazz);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Padding = new System.Windows.Forms.Padding(20);
            this.panel2.Size = new System.Drawing.Size(1259, 100);
            this.panel2.TabIndex = 2;
            // 
            // btnBTS
            // 
            this.btnBTS.AllowAnimations = true;
            this.btnBTS.AllowMouseEffects = true;
            this.btnBTS.AllowToggling = true;
            this.btnBTS.AnimationSpeed = 200;
            this.btnBTS.AutoGenerateColors = false;
            this.btnBTS.AutoRoundBorders = true;
            this.btnBTS.AutoSizeLeftIcon = true;
            this.btnBTS.AutoSizeRightIcon = true;
            this.btnBTS.BackColor = System.Drawing.Color.Transparent;
            this.btnBTS.BackColor1 = System.Drawing.Color.White;
            this.btnBTS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBTS.BackgroundImage")));
            this.btnBTS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBTS.ButtonText = "BTS";
            this.btnBTS.ButtonTextMarginLeft = 0;
            this.btnBTS.ColorContrastOnClick = 45;
            this.btnBTS.ColorContrastOnHover = 45;
            this.btnBTS.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnBTS.CustomizableEdges = borderEdges1;
            this.btnBTS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBTS.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBTS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBTS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBTS.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnBTS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBTS.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBTS.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnBTS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBTS.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBTS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBTS.IconMarginLeft = 11;
            this.btnBTS.IconPadding = 10;
            this.btnBTS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBTS.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBTS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBTS.IconSize = 25;
            this.btnBTS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnBTS.IdleBorderRadius = 58;
            this.btnBTS.IdleBorderThickness = 1;
            this.btnBTS.IdleFillColor = System.Drawing.Color.White;
            this.btnBTS.IdleIconLeftImage = null;
            this.btnBTS.IdleIconRightImage = null;
            this.btnBTS.IndicateFocus = true;
            this.btnBTS.Location = new System.Drawing.Point(920, 20);
            this.btnBTS.Name = "btnBTS";
            this.btnBTS.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBTS.OnDisabledState.BorderRadius = 1;
            this.btnBTS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBTS.OnDisabledState.BorderThickness = 1;
            this.btnBTS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBTS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBTS.OnDisabledState.IconLeftImage = null;
            this.btnBTS.OnDisabledState.IconRightImage = null;
            this.btnBTS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnBTS.onHoverState.BorderRadius = 1;
            this.btnBTS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBTS.onHoverState.BorderThickness = 1;
            this.btnBTS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnBTS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBTS.onHoverState.IconLeftImage = null;
            this.btnBTS.onHoverState.IconRightImage = null;
            this.btnBTS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnBTS.OnIdleState.BorderRadius = 1;
            this.btnBTS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBTS.OnIdleState.BorderThickness = 1;
            this.btnBTS.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnBTS.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnBTS.OnIdleState.IconLeftImage = null;
            this.btnBTS.OnIdleState.IconRightImage = null;
            this.btnBTS.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnBTS.OnPressedState.BorderRadius = 1;
            this.btnBTS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBTS.OnPressedState.BorderThickness = 1;
            this.btnBTS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnBTS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBTS.OnPressedState.IconLeftImage = null;
            this.btnBTS.OnPressedState.IconRightImage = null;
            this.btnBTS.Size = new System.Drawing.Size(150, 60);
            this.btnBTS.TabIndex = 6;
            this.btnBTS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBTS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBTS.TextMarginLeft = 0;
            this.btnBTS.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBTS.UseDefaultRadiusAndThickness = true;
            this.btnBTS.Click += new System.EventHandler(this.btnBTS_Click);
            // 
            // btnCustom
            // 
            this.btnCustom.AllowAnimations = true;
            this.btnCustom.AllowMouseEffects = true;
            this.btnCustom.AllowToggling = true;
            this.btnCustom.AnimationSpeed = 200;
            this.btnCustom.AutoGenerateColors = false;
            this.btnCustom.AutoRoundBorders = true;
            this.btnCustom.AutoSizeLeftIcon = true;
            this.btnCustom.AutoSizeRightIcon = true;
            this.btnCustom.BackColor = System.Drawing.Color.Transparent;
            this.btnCustom.BackColor1 = System.Drawing.Color.White;
            this.btnCustom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCustom.BackgroundImage")));
            this.btnCustom.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustom.ButtonText = "Custom CDR";
            this.btnCustom.ButtonTextMarginLeft = 0;
            this.btnCustom.ColorContrastOnClick = 45;
            this.btnCustom.ColorContrastOnHover = 45;
            this.btnCustom.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCustom.CustomizableEdges = borderEdges2;
            this.btnCustom.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCustom.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustom.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustom.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustom.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnCustom.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCustom.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCustom.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCustom.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCustom.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustom.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCustom.IconMarginLeft = 11;
            this.btnCustom.IconPadding = 10;
            this.btnCustom.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCustom.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustom.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCustom.IconSize = 25;
            this.btnCustom.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCustom.IdleBorderRadius = 58;
            this.btnCustom.IdleBorderThickness = 1;
            this.btnCustom.IdleFillColor = System.Drawing.Color.White;
            this.btnCustom.IdleIconLeftImage = null;
            this.btnCustom.IdleIconRightImage = null;
            this.btnCustom.IndicateFocus = true;
            this.btnCustom.Location = new System.Drawing.Point(770, 20);
            this.btnCustom.Name = "btnCustom";
            this.btnCustom.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustom.OnDisabledState.BorderRadius = 1;
            this.btnCustom.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustom.OnDisabledState.BorderThickness = 1;
            this.btnCustom.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustom.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustom.OnDisabledState.IconLeftImage = null;
            this.btnCustom.OnDisabledState.IconRightImage = null;
            this.btnCustom.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCustom.onHoverState.BorderRadius = 1;
            this.btnCustom.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustom.onHoverState.BorderThickness = 1;
            this.btnCustom.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCustom.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCustom.onHoverState.IconLeftImage = null;
            this.btnCustom.onHoverState.IconRightImage = null;
            this.btnCustom.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCustom.OnIdleState.BorderRadius = 1;
            this.btnCustom.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustom.OnIdleState.BorderThickness = 1;
            this.btnCustom.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnCustom.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCustom.OnIdleState.IconLeftImage = null;
            this.btnCustom.OnIdleState.IconRightImage = null;
            this.btnCustom.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCustom.OnPressedState.BorderRadius = 1;
            this.btnCustom.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustom.OnPressedState.BorderThickness = 1;
            this.btnCustom.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCustom.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCustom.OnPressedState.IconLeftImage = null;
            this.btnCustom.OnPressedState.IconRightImage = null;
            this.btnCustom.Size = new System.Drawing.Size(150, 60);
            this.btnCustom.TabIndex = 5;
            this.btnCustom.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCustom.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCustom.TextMarginLeft = 0;
            this.btnCustom.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCustom.UseDefaultRadiusAndThickness = true;
            this.btnCustom.Click += new System.EventHandler(this.btnCustom_Click);
            // 
            // btnTelenor
            // 
            this.btnTelenor.AllowAnimations = true;
            this.btnTelenor.AllowMouseEffects = true;
            this.btnTelenor.AllowToggling = true;
            this.btnTelenor.AnimationSpeed = 200;
            this.btnTelenor.AutoGenerateColors = false;
            this.btnTelenor.AutoRoundBorders = true;
            this.btnTelenor.AutoSizeLeftIcon = true;
            this.btnTelenor.AutoSizeRightIcon = true;
            this.btnTelenor.BackColor = System.Drawing.Color.Transparent;
            this.btnTelenor.BackColor1 = System.Drawing.Color.White;
            this.btnTelenor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTelenor.BackgroundImage")));
            this.btnTelenor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTelenor.ButtonText = "Telenor";
            this.btnTelenor.ButtonTextMarginLeft = 0;
            this.btnTelenor.ColorContrastOnClick = 45;
            this.btnTelenor.ColorContrastOnHover = 45;
            this.btnTelenor.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnTelenor.CustomizableEdges = borderEdges3;
            this.btnTelenor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTelenor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTelenor.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTelenor.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTelenor.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnTelenor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTelenor.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnTelenor.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnTelenor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTelenor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTelenor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTelenor.IconMarginLeft = 11;
            this.btnTelenor.IconPadding = 10;
            this.btnTelenor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTelenor.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTelenor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTelenor.IconSize = 25;
            this.btnTelenor.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnTelenor.IdleBorderRadius = 58;
            this.btnTelenor.IdleBorderThickness = 1;
            this.btnTelenor.IdleFillColor = System.Drawing.Color.White;
            this.btnTelenor.IdleIconLeftImage = null;
            this.btnTelenor.IdleIconRightImage = null;
            this.btnTelenor.IndicateFocus = true;
            this.btnTelenor.Location = new System.Drawing.Point(620, 20);
            this.btnTelenor.Name = "btnTelenor";
            this.btnTelenor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTelenor.OnDisabledState.BorderRadius = 1;
            this.btnTelenor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTelenor.OnDisabledState.BorderThickness = 1;
            this.btnTelenor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTelenor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTelenor.OnDisabledState.IconLeftImage = null;
            this.btnTelenor.OnDisabledState.IconRightImage = null;
            this.btnTelenor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnTelenor.onHoverState.BorderRadius = 1;
            this.btnTelenor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTelenor.onHoverState.BorderThickness = 1;
            this.btnTelenor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnTelenor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTelenor.onHoverState.IconLeftImage = null;
            this.btnTelenor.onHoverState.IconRightImage = null;
            this.btnTelenor.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnTelenor.OnIdleState.BorderRadius = 1;
            this.btnTelenor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTelenor.OnIdleState.BorderThickness = 1;
            this.btnTelenor.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnTelenor.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnTelenor.OnIdleState.IconLeftImage = null;
            this.btnTelenor.OnIdleState.IconRightImage = null;
            this.btnTelenor.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnTelenor.OnPressedState.BorderRadius = 1;
            this.btnTelenor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTelenor.OnPressedState.BorderThickness = 1;
            this.btnTelenor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnTelenor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTelenor.OnPressedState.IconLeftImage = null;
            this.btnTelenor.OnPressedState.IconRightImage = null;
            this.btnTelenor.Size = new System.Drawing.Size(150, 60);
            this.btnTelenor.TabIndex = 4;
            this.btnTelenor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTelenor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTelenor.TextMarginLeft = 0;
            this.btnTelenor.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTelenor.UseDefaultRadiusAndThickness = true;
            this.btnTelenor.Click += new System.EventHandler(this.btnTelenor_Click);
            // 
            // btnUfone
            // 
            this.btnUfone.AllowAnimations = true;
            this.btnUfone.AllowMouseEffects = true;
            this.btnUfone.AllowToggling = true;
            this.btnUfone.AnimationSpeed = 200;
            this.btnUfone.AutoGenerateColors = false;
            this.btnUfone.AutoRoundBorders = true;
            this.btnUfone.AutoSizeLeftIcon = true;
            this.btnUfone.AutoSizeRightIcon = true;
            this.btnUfone.BackColor = System.Drawing.Color.Transparent;
            this.btnUfone.BackColor1 = System.Drawing.Color.White;
            this.btnUfone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUfone.BackgroundImage")));
            this.btnUfone.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUfone.ButtonText = "Ufone";
            this.btnUfone.ButtonTextMarginLeft = 0;
            this.btnUfone.ColorContrastOnClick = 45;
            this.btnUfone.ColorContrastOnHover = 45;
            this.btnUfone.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnUfone.CustomizableEdges = borderEdges4;
            this.btnUfone.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUfone.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUfone.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUfone.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUfone.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnUfone.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUfone.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnUfone.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnUfone.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUfone.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUfone.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUfone.IconMarginLeft = 11;
            this.btnUfone.IconPadding = 10;
            this.btnUfone.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUfone.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUfone.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUfone.IconSize = 25;
            this.btnUfone.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnUfone.IdleBorderRadius = 58;
            this.btnUfone.IdleBorderThickness = 1;
            this.btnUfone.IdleFillColor = System.Drawing.Color.White;
            this.btnUfone.IdleIconLeftImage = null;
            this.btnUfone.IdleIconRightImage = null;
            this.btnUfone.IndicateFocus = true;
            this.btnUfone.Location = new System.Drawing.Point(470, 20);
            this.btnUfone.Name = "btnUfone";
            this.btnUfone.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUfone.OnDisabledState.BorderRadius = 1;
            this.btnUfone.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUfone.OnDisabledState.BorderThickness = 1;
            this.btnUfone.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUfone.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUfone.OnDisabledState.IconLeftImage = null;
            this.btnUfone.OnDisabledState.IconRightImage = null;
            this.btnUfone.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnUfone.onHoverState.BorderRadius = 1;
            this.btnUfone.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUfone.onHoverState.BorderThickness = 1;
            this.btnUfone.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnUfone.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUfone.onHoverState.IconLeftImage = null;
            this.btnUfone.onHoverState.IconRightImage = null;
            this.btnUfone.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnUfone.OnIdleState.BorderRadius = 1;
            this.btnUfone.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUfone.OnIdleState.BorderThickness = 1;
            this.btnUfone.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnUfone.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnUfone.OnIdleState.IconLeftImage = null;
            this.btnUfone.OnIdleState.IconRightImage = null;
            this.btnUfone.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnUfone.OnPressedState.BorderRadius = 1;
            this.btnUfone.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUfone.OnPressedState.BorderThickness = 1;
            this.btnUfone.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnUfone.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUfone.OnPressedState.IconLeftImage = null;
            this.btnUfone.OnPressedState.IconRightImage = null;
            this.btnUfone.Size = new System.Drawing.Size(150, 60);
            this.btnUfone.TabIndex = 3;
            this.btnUfone.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUfone.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUfone.TextMarginLeft = 0;
            this.btnUfone.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUfone.UseDefaultRadiusAndThickness = true;
            this.btnUfone.Click += new System.EventHandler(this.btnUfone_Click);
            // 
            // btnZong
            // 
            this.btnZong.AllowAnimations = true;
            this.btnZong.AllowMouseEffects = true;
            this.btnZong.AllowToggling = true;
            this.btnZong.AnimationSpeed = 200;
            this.btnZong.AutoGenerateColors = false;
            this.btnZong.AutoRoundBorders = true;
            this.btnZong.AutoSizeLeftIcon = true;
            this.btnZong.AutoSizeRightIcon = true;
            this.btnZong.BackColor = System.Drawing.Color.Transparent;
            this.btnZong.BackColor1 = System.Drawing.Color.White;
            this.btnZong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnZong.BackgroundImage")));
            this.btnZong.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnZong.ButtonText = "Zong";
            this.btnZong.ButtonTextMarginLeft = 0;
            this.btnZong.ColorContrastOnClick = 45;
            this.btnZong.ColorContrastOnHover = 45;
            this.btnZong.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnZong.CustomizableEdges = borderEdges5;
            this.btnZong.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnZong.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnZong.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnZong.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnZong.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnZong.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnZong.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnZong.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnZong.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnZong.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnZong.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnZong.IconMarginLeft = 11;
            this.btnZong.IconPadding = 10;
            this.btnZong.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnZong.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnZong.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnZong.IconSize = 25;
            this.btnZong.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnZong.IdleBorderRadius = 58;
            this.btnZong.IdleBorderThickness = 1;
            this.btnZong.IdleFillColor = System.Drawing.Color.White;
            this.btnZong.IdleIconLeftImage = null;
            this.btnZong.IdleIconRightImage = null;
            this.btnZong.IndicateFocus = true;
            this.btnZong.Location = new System.Drawing.Point(320, 20);
            this.btnZong.Name = "btnZong";
            this.btnZong.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnZong.OnDisabledState.BorderRadius = 1;
            this.btnZong.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnZong.OnDisabledState.BorderThickness = 1;
            this.btnZong.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnZong.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnZong.OnDisabledState.IconLeftImage = null;
            this.btnZong.OnDisabledState.IconRightImage = null;
            this.btnZong.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnZong.onHoverState.BorderRadius = 1;
            this.btnZong.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnZong.onHoverState.BorderThickness = 1;
            this.btnZong.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnZong.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnZong.onHoverState.IconLeftImage = null;
            this.btnZong.onHoverState.IconRightImage = null;
            this.btnZong.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnZong.OnIdleState.BorderRadius = 1;
            this.btnZong.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnZong.OnIdleState.BorderThickness = 1;
            this.btnZong.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnZong.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnZong.OnIdleState.IconLeftImage = null;
            this.btnZong.OnIdleState.IconRightImage = null;
            this.btnZong.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnZong.OnPressedState.BorderRadius = 1;
            this.btnZong.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnZong.OnPressedState.BorderThickness = 1;
            this.btnZong.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnZong.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnZong.OnPressedState.IconLeftImage = null;
            this.btnZong.OnPressedState.IconRightImage = null;
            this.btnZong.Size = new System.Drawing.Size(150, 60);
            this.btnZong.TabIndex = 2;
            this.btnZong.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnZong.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnZong.TextMarginLeft = 0;
            this.btnZong.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnZong.UseDefaultRadiusAndThickness = true;
            this.btnZong.Click += new System.EventHandler(this.btnZong_Click);
            // 
            // btnWarid
            // 
            this.btnWarid.AllowAnimations = true;
            this.btnWarid.AllowMouseEffects = true;
            this.btnWarid.AllowToggling = true;
            this.btnWarid.AnimationSpeed = 200;
            this.btnWarid.AutoGenerateColors = false;
            this.btnWarid.AutoRoundBorders = true;
            this.btnWarid.AutoSizeLeftIcon = true;
            this.btnWarid.AutoSizeRightIcon = true;
            this.btnWarid.BackColor = System.Drawing.Color.Transparent;
            this.btnWarid.BackColor1 = System.Drawing.Color.White;
            this.btnWarid.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnWarid.BackgroundImage")));
            this.btnWarid.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarid.ButtonText = "Warid";
            this.btnWarid.ButtonTextMarginLeft = 0;
            this.btnWarid.ColorContrastOnClick = 45;
            this.btnWarid.ColorContrastOnHover = 45;
            this.btnWarid.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnWarid.CustomizableEdges = borderEdges6;
            this.btnWarid.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnWarid.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWarid.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnWarid.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnWarid.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnWarid.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnWarid.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnWarid.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnWarid.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnWarid.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnWarid.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnWarid.IconMarginLeft = 11;
            this.btnWarid.IconPadding = 10;
            this.btnWarid.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnWarid.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnWarid.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnWarid.IconSize = 25;
            this.btnWarid.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnWarid.IdleBorderRadius = 58;
            this.btnWarid.IdleBorderThickness = 1;
            this.btnWarid.IdleFillColor = System.Drawing.Color.White;
            this.btnWarid.IdleIconLeftImage = null;
            this.btnWarid.IdleIconRightImage = null;
            this.btnWarid.IndicateFocus = true;
            this.btnWarid.Location = new System.Drawing.Point(170, 20);
            this.btnWarid.Name = "btnWarid";
            this.btnWarid.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWarid.OnDisabledState.BorderRadius = 1;
            this.btnWarid.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarid.OnDisabledState.BorderThickness = 1;
            this.btnWarid.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnWarid.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnWarid.OnDisabledState.IconLeftImage = null;
            this.btnWarid.OnDisabledState.IconRightImage = null;
            this.btnWarid.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnWarid.onHoverState.BorderRadius = 1;
            this.btnWarid.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarid.onHoverState.BorderThickness = 1;
            this.btnWarid.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnWarid.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnWarid.onHoverState.IconLeftImage = null;
            this.btnWarid.onHoverState.IconRightImage = null;
            this.btnWarid.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnWarid.OnIdleState.BorderRadius = 1;
            this.btnWarid.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarid.OnIdleState.BorderThickness = 1;
            this.btnWarid.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnWarid.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnWarid.OnIdleState.IconLeftImage = null;
            this.btnWarid.OnIdleState.IconRightImage = null;
            this.btnWarid.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnWarid.OnPressedState.BorderRadius = 1;
            this.btnWarid.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarid.OnPressedState.BorderThickness = 1;
            this.btnWarid.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnWarid.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnWarid.OnPressedState.IconLeftImage = null;
            this.btnWarid.OnPressedState.IconRightImage = null;
            this.btnWarid.Size = new System.Drawing.Size(150, 60);
            this.btnWarid.TabIndex = 1;
            this.btnWarid.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnWarid.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnWarid.TextMarginLeft = 0;
            this.btnWarid.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnWarid.UseDefaultRadiusAndThickness = true;
            this.btnWarid.Click += new System.EventHandler(this.btnWarid_Click);
            // 
            // btnJazz
            // 
            this.btnJazz.AllowAnimations = true;
            this.btnJazz.AllowMouseEffects = true;
            this.btnJazz.AllowToggling = true;
            this.btnJazz.AnimationSpeed = 200;
            this.btnJazz.AutoGenerateColors = false;
            this.btnJazz.AutoRoundBorders = true;
            this.btnJazz.AutoSizeLeftIcon = true;
            this.btnJazz.AutoSizeRightIcon = true;
            this.btnJazz.BackColor = System.Drawing.Color.Transparent;
            this.btnJazz.BackColor1 = System.Drawing.Color.White;
            this.btnJazz.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnJazz.BackgroundImage")));
            this.btnJazz.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJazz.ButtonText = "Jazz";
            this.btnJazz.ButtonTextMarginLeft = 0;
            this.btnJazz.ColorContrastOnClick = 45;
            this.btnJazz.ColorContrastOnHover = 45;
            this.btnJazz.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnJazz.CustomizableEdges = borderEdges7;
            this.btnJazz.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnJazz.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJazz.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJazz.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJazz.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnJazz.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnJazz.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnJazz.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnJazz.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnJazz.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnJazz.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnJazz.IconMarginLeft = 11;
            this.btnJazz.IconPadding = 10;
            this.btnJazz.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnJazz.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnJazz.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnJazz.IconSize = 25;
            this.btnJazz.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnJazz.IdleBorderRadius = 58;
            this.btnJazz.IdleBorderThickness = 1;
            this.btnJazz.IdleFillColor = System.Drawing.Color.White;
            this.btnJazz.IdleIconLeftImage = null;
            this.btnJazz.IdleIconRightImage = null;
            this.btnJazz.IndicateFocus = true;
            this.btnJazz.Location = new System.Drawing.Point(20, 20);
            this.btnJazz.Name = "btnJazz";
            this.btnJazz.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJazz.OnDisabledState.BorderRadius = 1;
            this.btnJazz.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJazz.OnDisabledState.BorderThickness = 1;
            this.btnJazz.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJazz.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJazz.OnDisabledState.IconLeftImage = null;
            this.btnJazz.OnDisabledState.IconRightImage = null;
            this.btnJazz.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnJazz.onHoverState.BorderRadius = 1;
            this.btnJazz.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJazz.onHoverState.BorderThickness = 1;
            this.btnJazz.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnJazz.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnJazz.onHoverState.IconLeftImage = null;
            this.btnJazz.onHoverState.IconRightImage = null;
            this.btnJazz.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnJazz.OnIdleState.BorderRadius = 1;
            this.btnJazz.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJazz.OnIdleState.BorderThickness = 1;
            this.btnJazz.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnJazz.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnJazz.OnIdleState.IconLeftImage = null;
            this.btnJazz.OnIdleState.IconRightImage = null;
            this.btnJazz.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnJazz.OnPressedState.BorderRadius = 1;
            this.btnJazz.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJazz.OnPressedState.BorderThickness = 1;
            this.btnJazz.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnJazz.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnJazz.OnPressedState.IconLeftImage = null;
            this.btnJazz.OnPressedState.IconRightImage = null;
            this.btnJazz.Size = new System.Drawing.Size(150, 60);
            this.btnJazz.TabIndex = 0;
            this.btnJazz.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnJazz.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnJazz.TextMarginLeft = 0;
            this.btnJazz.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnJazz.UseDefaultRadiusAndThickness = true;
            this.btnJazz.Click += new System.EventHandler(this.btnJazz_Click);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.lbVideoLectureDownload);
            this.panel1.Controls.Add(this.lbSampleDownload);
            this.panel1.Controls.Add(this.gvFormatCDR);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 100);
            this.panel1.Name = "panel1";
            this.panel1.Padding = new System.Windows.Forms.Padding(25);
            this.panel1.Size = new System.Drawing.Size(1259, 657);
            this.panel1.TabIndex = 3;
            // 
            // gvFormatCDR
            // 
            this.gvFormatCDR.BackgroundColor = System.Drawing.Color.White;
            this.gvFormatCDR.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gvFormatCDR.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gvFormatCDR.EnableHeadersVisualStyles = false;
            this.gvFormatCDR.GridColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.gvFormatCDR.Location = new System.Drawing.Point(25, 25);
            this.gvFormatCDR.Name = "gvFormatCDR";
            this.gvFormatCDR.RowHeadersVisible = false;
            this.gvFormatCDR.Size = new System.Drawing.Size(1209, 607);
            this.gvFormatCDR.TabIndex = 0;
            // 
            // lbSampleDownload
            // 
            this.lbSampleDownload.AutoSize = true;
            this.lbSampleDownload.Location = new System.Drawing.Point(22, 3);
            this.lbSampleDownload.Name = "lbSampleDownload";
            this.lbSampleDownload.Size = new System.Drawing.Size(93, 13);
            this.lbSampleDownload.TabIndex = 1;
            this.lbSampleDownload.TabStop = true;
            this.lbSampleDownload.Text = "Sample Download";
            this.lbSampleDownload.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lbSampleDownload_LinkClicked);
            // 
            // lbVideoLectureDownload
            // 
            this.lbVideoLectureDownload.AutoSize = true;
            this.lbVideoLectureDownload.Location = new System.Drawing.Point(167, 3);
            this.lbVideoLectureDownload.Name = "lbVideoLectureDownload";
            this.lbVideoLectureDownload.Size = new System.Drawing.Size(124, 13);
            this.lbVideoLectureDownload.TabIndex = 2;
            this.lbVideoLectureDownload.TabStop = true;
            this.lbVideoLectureDownload.Text = "Video Lecture Download";
            this.lbVideoLectureDownload.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lbVideoLecture_LinkClicked);
            // 
            // CDRFormatForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(245)))), ((int)(((byte)(244)))));
            this.ClientSize = new System.Drawing.Size(1259, 757);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panel2);
            this.Name = "CDRFormatForm";
            this.Text = "CUSTOM FORMAT";
            this.panel2.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gvFormatCDR)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTelenor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUfone;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnZong;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnWarid;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnJazz;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.DataGridView gvFormatCDR;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBTS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCustom;
        private System.Windows.Forms.LinkLabel lbSampleDownload;
        private System.Windows.Forms.LinkLabel lbVideoLectureDownload;
    }
}