namespace ReadExcelApp.Forms
{
    partial class LoginForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.label1 = new System.Windows.Forms.Label();
            this.lbVersion = new System.Windows.Forms.Label();
            this.bcLogin = new Bunifu.Framework.UI.BunifuCards();
            this.btnRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUserName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbExit = new System.Windows.Forms.Label();
            this.bcRegisteration = new Bunifu.Framework.UI.BunifuCards();
            this.txtRegRePassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnLoginForm = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCreateAccount = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtRegPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtRegUserName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bcLogin.SuspendLayout();
            this.bcRegisteration.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse
            // 
            this.bunifuElipse.ElipseRadius = 25;
            this.bunifuElipse.TargetControl = this;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Bauhaus 93", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(103, 129);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(108, 36);
            this.label1.TabIndex = 9;
            this.label1.Text = "LOG IN";
            // 
            // lbVersion
            // 
            this.lbVersion.AutoSize = true;
            this.lbVersion.ForeColor = System.Drawing.Color.White;
            this.lbVersion.Location = new System.Drawing.Point(12, 9);
            this.lbVersion.Name = "lbVersion";
            this.lbVersion.Size = new System.Drawing.Size(0, 13);
            this.lbVersion.TabIndex = 18;
            // 
            // bcLogin
            // 
            this.bcLogin.BackColor = System.Drawing.Color.Wheat;
            this.bcLogin.BorderRadius = 20;
            this.bcLogin.BottomSahddow = true;
            this.bcLogin.color = System.Drawing.Color.Wheat;
            this.bcLogin.Controls.Add(this.btnRegister);
            this.bcLogin.Controls.Add(this.btnLogin);
            this.bcLogin.Controls.Add(this.txtPassword);
            this.bcLogin.Controls.Add(this.txtUserName);
            this.bcLogin.LeftSahddow = false;
            this.bcLogin.Location = new System.Drawing.Point(10, 168);
            this.bcLogin.Name = "bcLogin";
            this.bcLogin.RightSahddow = true;
            this.bcLogin.ShadowDepth = 20;
            this.bcLogin.Size = new System.Drawing.Size(284, 306);
            this.bcLogin.TabIndex = 19;
            this.bcLogin.Visible = false;
            // 
            // btnRegister
            // 
            this.btnRegister.AllowAnimations = true;
            this.btnRegister.AllowMouseEffects = true;
            this.btnRegister.AllowToggling = false;
            this.btnRegister.AnimationSpeed = 200;
            this.btnRegister.AutoGenerateColors = false;
            this.btnRegister.AutoRoundBorders = false;
            this.btnRegister.AutoSizeLeftIcon = true;
            this.btnRegister.AutoSizeRightIcon = true;
            this.btnRegister.BackColor = System.Drawing.Color.Transparent;
            this.btnRegister.BackColor1 = System.Drawing.Color.White;
            this.btnRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRegister.BackgroundImage")));
            this.btnRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.ButtonText = "Register";
            this.btnRegister.ButtonTextMarginLeft = 0;
            this.btnRegister.ColorContrastOnClick = 45;
            this.btnRegister.ColorContrastOnHover = 45;
            this.btnRegister.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnRegister.CustomizableEdges = borderEdges3;
            this.btnRegister.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRegister.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegister.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegister.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRegister.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.btnRegister.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnRegister.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRegister.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegister.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRegister.IconMarginLeft = 11;
            this.btnRegister.IconPadding = 10;
            this.btnRegister.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRegister.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegister.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRegister.IconSize = 25;
            this.btnRegister.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnRegister.IdleBorderRadius = 4;
            this.btnRegister.IdleBorderThickness = 2;
            this.btnRegister.IdleFillColor = System.Drawing.Color.White;
            this.btnRegister.IdleIconLeftImage = null;
            this.btnRegister.IdleIconRightImage = null;
            this.btnRegister.IndicateFocus = false;
            this.btnRegister.Location = new System.Drawing.Point(17, 241);
            this.btnRegister.Name = "btnRegister";
            this.btnRegister.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegister.OnDisabledState.BorderRadius = 4;
            this.btnRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.OnDisabledState.BorderThickness = 2;
            this.btnRegister.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegister.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegister.OnDisabledState.IconLeftImage = null;
            this.btnRegister.OnDisabledState.IconRightImage = null;
            this.btnRegister.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnRegister.onHoverState.BorderRadius = 4;
            this.btnRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.onHoverState.BorderThickness = 2;
            this.btnRegister.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnRegister.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnRegister.onHoverState.IconLeftImage = null;
            this.btnRegister.onHoverState.IconRightImage = null;
            this.btnRegister.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnRegister.OnIdleState.BorderRadius = 4;
            this.btnRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.OnIdleState.BorderThickness = 2;
            this.btnRegister.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnRegister.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnRegister.OnIdleState.IconLeftImage = null;
            this.btnRegister.OnIdleState.IconRightImage = null;
            this.btnRegister.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnRegister.OnPressedState.BorderRadius = 4;
            this.btnRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.OnPressedState.BorderThickness = 2;
            this.btnRegister.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnRegister.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnRegister.OnPressedState.IconLeftImage = null;
            this.btnRegister.OnPressedState.IconRightImage = null;
            this.btnRegister.Size = new System.Drawing.Size(249, 39);
            this.btnRegister.TabIndex = 55;
            this.btnRegister.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRegister.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRegister.TextMarginLeft = 0;
            this.btnRegister.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRegister.UseDefaultRadiusAndThickness = true;
            this.btnRegister.Click += new System.EventHandler(this.btnRegister_Click);
            // 
            // btnLogin
            // 
            this.btnLogin.AllowAnimations = true;
            this.btnLogin.AllowMouseEffects = true;
            this.btnLogin.AllowToggling = false;
            this.btnLogin.AnimationSpeed = 200;
            this.btnLogin.AutoGenerateColors = false;
            this.btnLogin.AutoRoundBorders = false;
            this.btnLogin.AutoSizeLeftIcon = true;
            this.btnLogin.AutoSizeRightIcon = true;
            this.btnLogin.BackColor = System.Drawing.Color.Transparent;
            this.btnLogin.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogin.BackgroundImage")));
            this.btnLogin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.ButtonText = "LOG IN";
            this.btnLogin.ButtonTextMarginLeft = 0;
            this.btnLogin.ColorContrastOnClick = 45;
            this.btnLogin.ColorContrastOnHover = 45;
            this.btnLogin.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnLogin.CustomizableEdges = borderEdges4;
            this.btnLogin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogin.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogin.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogin.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold);
            this.btnLogin.ForeColor = System.Drawing.Color.White;
            this.btnLogin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogin.IconMarginLeft = 11;
            this.btnLogin.IconPadding = 10;
            this.btnLogin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogin.IconSize = 25;
            this.btnLogin.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLogin.IdleBorderRadius = 4;
            this.btnLogin.IdleBorderThickness = 2;
            this.btnLogin.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLogin.IdleIconLeftImage = null;
            this.btnLogin.IdleIconRightImage = null;
            this.btnLogin.IndicateFocus = false;
            this.btnLogin.Location = new System.Drawing.Point(17, 196);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogin.OnDisabledState.BorderRadius = 4;
            this.btnLogin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnDisabledState.BorderThickness = 2;
            this.btnLogin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogin.OnDisabledState.IconLeftImage = null;
            this.btnLogin.OnDisabledState.IconRightImage = null;
            this.btnLogin.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnLogin.onHoverState.BorderRadius = 4;
            this.btnLogin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.onHoverState.BorderThickness = 2;
            this.btnLogin.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLogin.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.onHoverState.IconLeftImage = null;
            this.btnLogin.onHoverState.IconRightImage = null;
            this.btnLogin.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLogin.OnIdleState.BorderRadius = 4;
            this.btnLogin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnIdleState.BorderThickness = 2;
            this.btnLogin.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLogin.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.OnIdleState.IconLeftImage = null;
            this.btnLogin.OnIdleState.IconRightImage = null;
            this.btnLogin.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnLogin.OnPressedState.BorderRadius = 4;
            this.btnLogin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnPressedState.BorderThickness = 2;
            this.btnLogin.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLogin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.OnPressedState.IconLeftImage = null;
            this.btnLogin.OnPressedState.IconRightImage = null;
            this.btnLogin.Size = new System.Drawing.Size(249, 39);
            this.btnLogin.TabIndex = 54;
            this.btnLogin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogin.TextMarginLeft = 0;
            this.btnLogin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLogin.UseDefaultRadiusAndThickness = true;
            this.btnLogin.Click += new System.EventHandler(this.btnLogin_Click);
            // 
            // txtPassword
            // 
            this.txtPassword.AcceptsReturn = false;
            this.txtPassword.AcceptsTab = false;
            this.txtPassword.AnimationSpeed = 200;
            this.txtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword.BackgroundImage")));
            this.txtPassword.BorderColorActive = System.Drawing.Color.White;
            this.txtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword.BorderColorHover = System.Drawing.Color.White;
            this.txtPassword.BorderColorIdle = System.Drawing.Color.DarkSlateGray;
            this.txtPassword.BorderRadius = 4;
            this.txtPassword.BorderThickness = 2;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 12F);
            this.txtPassword.DefaultText = "";
            this.txtPassword.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.txtPassword.ForeColor = System.Drawing.Color.White;
            this.txtPassword.HideSelection = true;
            this.txtPassword.IconLeft = global::ReadExcelApp.Properties.Resources.padlock;
            this.txtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.IconPadding = 10;
            this.txtPassword.IconRight = global::ReadExcelApp.Properties.Resources.eye_grey;
            this.txtPassword.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.txtPassword.Lines = new string[0];
            this.txtPassword.Location = new System.Drawing.Point(17, 94);
            this.txtPassword.MaxLength = 32767;
            this.txtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPassword.Modified = false;
            this.txtPassword.Multiline = false;
            this.txtPassword.Name = "txtPassword";
            stateProperties13.BorderColor = System.Drawing.Color.White;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.White;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.DarkSlateGray;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnIdleState = stateProperties16;
            this.txtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtPassword.PasswordChar = '\0';
            this.txtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword.PlaceholderText = "Enter Password";
            this.txtPassword.ReadOnly = false;
            this.txtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(249, 50);
            this.txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword.TabIndex = 2;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TextMarginBottom = 0;
            this.txtPassword.TextMarginLeft = 3;
            this.txtPassword.TextMarginTop = 0;
            this.txtPassword.TextPlaceholder = "Enter Password";
            this.txtPassword.UseSystemPasswordChar = false;
            this.txtPassword.WordWrap = true;
            this.txtPassword.TextChange += new System.EventHandler(this.txtPassword_TextChange);
            this.txtPassword.OnIconRightClick += new System.EventHandler(this.txtPassword_OnIconRightClick);
            this.txtPassword.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtPassword_KeyDown);
            // 
            // txtUserName
            // 
            this.txtUserName.AcceptsReturn = false;
            this.txtUserName.AcceptsTab = false;
            this.txtUserName.AnimationSpeed = 200;
            this.txtUserName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUserName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUserName.BackColor = System.Drawing.Color.Transparent;
            this.txtUserName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUserName.BackgroundImage")));
            this.txtUserName.BorderColorActive = System.Drawing.Color.White;
            this.txtUserName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUserName.BorderColorHover = System.Drawing.Color.White;
            this.txtUserName.BorderColorIdle = System.Drawing.Color.DarkSlateGray;
            this.txtUserName.BorderRadius = 4;
            this.txtUserName.BorderThickness = 2;
            this.txtUserName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUserName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserName.DefaultFont = new System.Drawing.Font("Segoe UI", 12F);
            this.txtUserName.DefaultText = "";
            this.txtUserName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.txtUserName.ForeColor = System.Drawing.Color.White;
            this.txtUserName.HideSelection = true;
            this.txtUserName.IconLeft = global::ReadExcelApp.Properties.Resources.user;
            this.txtUserName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserName.IconPadding = 10;
            this.txtUserName.IconRight = null;
            this.txtUserName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserName.Lines = new string[0];
            this.txtUserName.Location = new System.Drawing.Point(17, 20);
            this.txtUserName.MaxLength = 32767;
            this.txtUserName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUserName.Modified = false;
            this.txtUserName.Multiline = false;
            this.txtUserName.Name = "txtUserName";
            stateProperties17.BorderColor = System.Drawing.Color.White;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUserName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.White;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.DarkSlateGray;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserName.OnIdleState = stateProperties20;
            this.txtUserName.Padding = new System.Windows.Forms.Padding(3);
            this.txtUserName.PasswordChar = '\0';
            this.txtUserName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUserName.PlaceholderText = "Enter Name";
            this.txtUserName.ReadOnly = false;
            this.txtUserName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUserName.SelectedText = "";
            this.txtUserName.SelectionLength = 0;
            this.txtUserName.SelectionStart = 0;
            this.txtUserName.ShortcutsEnabled = true;
            this.txtUserName.Size = new System.Drawing.Size(249, 50);
            this.txtUserName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUserName.TabIndex = 1;
            this.txtUserName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUserName.TextMarginBottom = 0;
            this.txtUserName.TextMarginLeft = 3;
            this.txtUserName.TextMarginTop = 0;
            this.txtUserName.TextPlaceholder = "Enter Name";
            this.txtUserName.UseSystemPasswordChar = false;
            this.txtUserName.WordWrap = true;
            // 
            // lbExit
            // 
            this.lbExit.AutoSize = true;
            this.lbExit.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbExit.ForeColor = System.Drawing.Color.White;
            this.lbExit.Location = new System.Drawing.Point(278, 5);
            this.lbExit.Name = "lbExit";
            this.lbExit.Size = new System.Drawing.Size(18, 17);
            this.lbExit.TabIndex = 6;
            this.lbExit.Text = "X";
            this.lbExit.Click += new System.EventHandler(this.lbExit_Click);
            // 
            // bcRegisteration
            // 
            this.bcRegisteration.BackColor = System.Drawing.Color.Wheat;
            this.bcRegisteration.BorderRadius = 20;
            this.bcRegisteration.BottomSahddow = true;
            this.bcRegisteration.color = System.Drawing.Color.Wheat;
            this.bcRegisteration.Controls.Add(this.txtRegRePassword);
            this.bcRegisteration.Controls.Add(this.btnLoginForm);
            this.bcRegisteration.Controls.Add(this.btnCreateAccount);
            this.bcRegisteration.Controls.Add(this.txtRegPassword);
            this.bcRegisteration.Controls.Add(this.txtRegUserName);
            this.bcRegisteration.LeftSahddow = false;
            this.bcRegisteration.Location = new System.Drawing.Point(12, 168);
            this.bcRegisteration.Name = "bcRegisteration";
            this.bcRegisteration.RightSahddow = true;
            this.bcRegisteration.ShadowDepth = 20;
            this.bcRegisteration.Size = new System.Drawing.Size(284, 306);
            this.bcRegisteration.TabIndex = 20;
            this.bcRegisteration.Visible = false;
            // 
            // txtRegRePassword
            // 
            this.txtRegRePassword.AcceptsReturn = false;
            this.txtRegRePassword.AcceptsTab = false;
            this.txtRegRePassword.AnimationSpeed = 200;
            this.txtRegRePassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRegRePassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRegRePassword.BackColor = System.Drawing.Color.Transparent;
            this.txtRegRePassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRegRePassword.BackgroundImage")));
            this.txtRegRePassword.BorderColorActive = System.Drawing.Color.White;
            this.txtRegRePassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRegRePassword.BorderColorHover = System.Drawing.Color.White;
            this.txtRegRePassword.BorderColorIdle = System.Drawing.Color.DarkSlateGray;
            this.txtRegRePassword.BorderRadius = 4;
            this.txtRegRePassword.BorderThickness = 2;
            this.txtRegRePassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRegRePassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegRePassword.DefaultFont = new System.Drawing.Font("Segoe UI", 12F);
            this.txtRegRePassword.DefaultText = "";
            this.txtRegRePassword.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.txtRegRePassword.ForeColor = System.Drawing.Color.White;
            this.txtRegRePassword.HideSelection = true;
            this.txtRegRePassword.IconLeft = global::ReadExcelApp.Properties.Resources.padlock;
            this.txtRegRePassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegRePassword.IconPadding = 10;
            this.txtRegRePassword.IconRight = global::ReadExcelApp.Properties.Resources.eye_grey;
            this.txtRegRePassword.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.txtRegRePassword.Lines = new string[0];
            this.txtRegRePassword.Location = new System.Drawing.Point(17, 140);
            this.txtRegRePassword.MaxLength = 32767;
            this.txtRegRePassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRegRePassword.Modified = false;
            this.txtRegRePassword.Multiline = false;
            this.txtRegRePassword.Name = "txtRegRePassword";
            stateProperties1.BorderColor = System.Drawing.Color.White;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegRePassword.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRegRePassword.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.White;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegRePassword.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DarkSlateGray;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegRePassword.OnIdleState = stateProperties4;
            this.txtRegRePassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtRegRePassword.PasswordChar = '\0';
            this.txtRegRePassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRegRePassword.PlaceholderText = "Reenter Password";
            this.txtRegRePassword.ReadOnly = false;
            this.txtRegRePassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRegRePassword.SelectedText = "";
            this.txtRegRePassword.SelectionLength = 0;
            this.txtRegRePassword.SelectionStart = 0;
            this.txtRegRePassword.ShortcutsEnabled = true;
            this.txtRegRePassword.Size = new System.Drawing.Size(249, 50);
            this.txtRegRePassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRegRePassword.TabIndex = 3;
            this.txtRegRePassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRegRePassword.TextMarginBottom = 0;
            this.txtRegRePassword.TextMarginLeft = 3;
            this.txtRegRePassword.TextMarginTop = 0;
            this.txtRegRePassword.TextPlaceholder = "Reenter Password";
            this.txtRegRePassword.UseSystemPasswordChar = false;
            this.txtRegRePassword.WordWrap = true;
            this.txtRegRePassword.TextChange += new System.EventHandler(this.txtRegRePassword_TextChange);
            this.txtRegRePassword.OnIconRightClick += new System.EventHandler(this.txtRegRePassword_OnIconRightClick);
            // 
            // btnLoginForm
            // 
            this.btnLoginForm.AllowAnimations = true;
            this.btnLoginForm.AllowMouseEffects = true;
            this.btnLoginForm.AllowToggling = false;
            this.btnLoginForm.AnimationSpeed = 200;
            this.btnLoginForm.AutoGenerateColors = false;
            this.btnLoginForm.AutoRoundBorders = false;
            this.btnLoginForm.AutoSizeLeftIcon = true;
            this.btnLoginForm.AutoSizeRightIcon = true;
            this.btnLoginForm.BackColor = System.Drawing.Color.Transparent;
            this.btnLoginForm.BackColor1 = System.Drawing.Color.White;
            this.btnLoginForm.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLoginForm.BackgroundImage")));
            this.btnLoginForm.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginForm.ButtonText = "Log In";
            this.btnLoginForm.ButtonTextMarginLeft = 0;
            this.btnLoginForm.ColorContrastOnClick = 45;
            this.btnLoginForm.ColorContrastOnHover = 45;
            this.btnLoginForm.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnLoginForm.CustomizableEdges = borderEdges1;
            this.btnLoginForm.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLoginForm.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoginForm.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoginForm.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoginForm.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLoginForm.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.btnLoginForm.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLoginForm.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLoginForm.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLoginForm.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLoginForm.IconMarginLeft = 11;
            this.btnLoginForm.IconPadding = 10;
            this.btnLoginForm.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLoginForm.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLoginForm.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLoginForm.IconSize = 25;
            this.btnLoginForm.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLoginForm.IdleBorderRadius = 4;
            this.btnLoginForm.IdleBorderThickness = 2;
            this.btnLoginForm.IdleFillColor = System.Drawing.Color.White;
            this.btnLoginForm.IdleIconLeftImage = null;
            this.btnLoginForm.IdleIconRightImage = null;
            this.btnLoginForm.IndicateFocus = false;
            this.btnLoginForm.Location = new System.Drawing.Point(17, 258);
            this.btnLoginForm.Name = "btnLoginForm";
            this.btnLoginForm.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoginForm.OnDisabledState.BorderRadius = 4;
            this.btnLoginForm.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginForm.OnDisabledState.BorderThickness = 2;
            this.btnLoginForm.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoginForm.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoginForm.OnDisabledState.IconLeftImage = null;
            this.btnLoginForm.OnDisabledState.IconRightImage = null;
            this.btnLoginForm.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnLoginForm.onHoverState.BorderRadius = 4;
            this.btnLoginForm.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginForm.onHoverState.BorderThickness = 2;
            this.btnLoginForm.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnLoginForm.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLoginForm.onHoverState.IconLeftImage = null;
            this.btnLoginForm.onHoverState.IconRightImage = null;
            this.btnLoginForm.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLoginForm.OnIdleState.BorderRadius = 4;
            this.btnLoginForm.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginForm.OnIdleState.BorderThickness = 2;
            this.btnLoginForm.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnLoginForm.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLoginForm.OnIdleState.IconLeftImage = null;
            this.btnLoginForm.OnIdleState.IconRightImage = null;
            this.btnLoginForm.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnLoginForm.OnPressedState.BorderRadius = 4;
            this.btnLoginForm.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginForm.OnPressedState.BorderThickness = 2;
            this.btnLoginForm.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnLoginForm.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnLoginForm.OnPressedState.IconLeftImage = null;
            this.btnLoginForm.OnPressedState.IconRightImage = null;
            this.btnLoginForm.Size = new System.Drawing.Size(249, 39);
            this.btnLoginForm.TabIndex = 5;
            this.btnLoginForm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLoginForm.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLoginForm.TextMarginLeft = 0;
            this.btnLoginForm.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLoginForm.UseDefaultRadiusAndThickness = true;
            this.btnLoginForm.Click += new System.EventHandler(this.btnLoginForm_Click);
            // 
            // btnCreateAccount
            // 
            this.btnCreateAccount.AllowAnimations = true;
            this.btnCreateAccount.AllowMouseEffects = true;
            this.btnCreateAccount.AllowToggling = false;
            this.btnCreateAccount.AnimationSpeed = 200;
            this.btnCreateAccount.AutoGenerateColors = false;
            this.btnCreateAccount.AutoRoundBorders = false;
            this.btnCreateAccount.AutoSizeLeftIcon = true;
            this.btnCreateAccount.AutoSizeRightIcon = true;
            this.btnCreateAccount.BackColor = System.Drawing.Color.Transparent;
            this.btnCreateAccount.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCreateAccount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCreateAccount.BackgroundImage")));
            this.btnCreateAccount.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateAccount.ButtonText = "CREATE ACCOUNT";
            this.btnCreateAccount.ButtonTextMarginLeft = 0;
            this.btnCreateAccount.ColorContrastOnClick = 45;
            this.btnCreateAccount.ColorContrastOnHover = 45;
            this.btnCreateAccount.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCreateAccount.CustomizableEdges = borderEdges2;
            this.btnCreateAccount.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCreateAccount.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCreateAccount.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCreateAccount.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCreateAccount.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCreateAccount.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold);
            this.btnCreateAccount.ForeColor = System.Drawing.Color.White;
            this.btnCreateAccount.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCreateAccount.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCreateAccount.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCreateAccount.IconMarginLeft = 11;
            this.btnCreateAccount.IconPadding = 10;
            this.btnCreateAccount.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCreateAccount.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCreateAccount.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCreateAccount.IconSize = 25;
            this.btnCreateAccount.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCreateAccount.IdleBorderRadius = 4;
            this.btnCreateAccount.IdleBorderThickness = 2;
            this.btnCreateAccount.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCreateAccount.IdleIconLeftImage = null;
            this.btnCreateAccount.IdleIconRightImage = null;
            this.btnCreateAccount.IndicateFocus = false;
            this.btnCreateAccount.Location = new System.Drawing.Point(17, 213);
            this.btnCreateAccount.Name = "btnCreateAccount";
            this.btnCreateAccount.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCreateAccount.OnDisabledState.BorderRadius = 4;
            this.btnCreateAccount.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateAccount.OnDisabledState.BorderThickness = 2;
            this.btnCreateAccount.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCreateAccount.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCreateAccount.OnDisabledState.IconLeftImage = null;
            this.btnCreateAccount.OnDisabledState.IconRightImage = null;
            this.btnCreateAccount.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnCreateAccount.onHoverState.BorderRadius = 4;
            this.btnCreateAccount.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateAccount.onHoverState.BorderThickness = 2;
            this.btnCreateAccount.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCreateAccount.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCreateAccount.onHoverState.IconLeftImage = null;
            this.btnCreateAccount.onHoverState.IconRightImage = null;
            this.btnCreateAccount.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCreateAccount.OnIdleState.BorderRadius = 4;
            this.btnCreateAccount.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateAccount.OnIdleState.BorderThickness = 2;
            this.btnCreateAccount.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCreateAccount.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCreateAccount.OnIdleState.IconLeftImage = null;
            this.btnCreateAccount.OnIdleState.IconRightImage = null;
            this.btnCreateAccount.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCreateAccount.OnPressedState.BorderRadius = 4;
            this.btnCreateAccount.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateAccount.OnPressedState.BorderThickness = 2;
            this.btnCreateAccount.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.btnCreateAccount.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCreateAccount.OnPressedState.IconLeftImage = null;
            this.btnCreateAccount.OnPressedState.IconRightImage = null;
            this.btnCreateAccount.Size = new System.Drawing.Size(249, 39);
            this.btnCreateAccount.TabIndex = 4;
            this.btnCreateAccount.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCreateAccount.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCreateAccount.TextMarginLeft = 0;
            this.btnCreateAccount.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCreateAccount.UseDefaultRadiusAndThickness = true;
            this.btnCreateAccount.Click += new System.EventHandler(this.btnCreateAccount_Click);
            // 
            // txtRegPassword
            // 
            this.txtRegPassword.AcceptsReturn = false;
            this.txtRegPassword.AcceptsTab = false;
            this.txtRegPassword.AnimationSpeed = 200;
            this.txtRegPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRegPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRegPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtRegPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRegPassword.BackgroundImage")));
            this.txtRegPassword.BorderColorActive = System.Drawing.Color.White;
            this.txtRegPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRegPassword.BorderColorHover = System.Drawing.Color.White;
            this.txtRegPassword.BorderColorIdle = System.Drawing.Color.DarkSlateGray;
            this.txtRegPassword.BorderRadius = 4;
            this.txtRegPassword.BorderThickness = 2;
            this.txtRegPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRegPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 12F);
            this.txtRegPassword.DefaultText = "";
            this.txtRegPassword.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.txtRegPassword.ForeColor = System.Drawing.Color.White;
            this.txtRegPassword.HideSelection = true;
            this.txtRegPassword.IconLeft = global::ReadExcelApp.Properties.Resources.padlock;
            this.txtRegPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegPassword.IconPadding = 10;
            this.txtRegPassword.IconRight = global::ReadExcelApp.Properties.Resources.eye_grey;
            this.txtRegPassword.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.txtRegPassword.Lines = new string[0];
            this.txtRegPassword.Location = new System.Drawing.Point(17, 84);
            this.txtRegPassword.MaxLength = 32767;
            this.txtRegPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRegPassword.Modified = false;
            this.txtRegPassword.Multiline = false;
            this.txtRegPassword.Name = "txtRegPassword";
            stateProperties5.BorderColor = System.Drawing.Color.White;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegPassword.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRegPassword.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.White;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegPassword.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.DarkSlateGray;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegPassword.OnIdleState = stateProperties8;
            this.txtRegPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtRegPassword.PasswordChar = '\0';
            this.txtRegPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRegPassword.PlaceholderText = "Enter Password";
            this.txtRegPassword.ReadOnly = false;
            this.txtRegPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRegPassword.SelectedText = "";
            this.txtRegPassword.SelectionLength = 0;
            this.txtRegPassword.SelectionStart = 0;
            this.txtRegPassword.ShortcutsEnabled = true;
            this.txtRegPassword.Size = new System.Drawing.Size(249, 50);
            this.txtRegPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRegPassword.TabIndex = 2;
            this.txtRegPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRegPassword.TextMarginBottom = 0;
            this.txtRegPassword.TextMarginLeft = 3;
            this.txtRegPassword.TextMarginTop = 0;
            this.txtRegPassword.TextPlaceholder = "Enter Password";
            this.txtRegPassword.UseSystemPasswordChar = false;
            this.txtRegPassword.WordWrap = true;
            this.txtRegPassword.TextChange += new System.EventHandler(this.txtRegPassword_TextChange);
            this.txtRegPassword.OnIconRightClick += new System.EventHandler(this.txtRegPassword_OnIconRightClick);
            // 
            // txtRegUserName
            // 
            this.txtRegUserName.AcceptsReturn = false;
            this.txtRegUserName.AcceptsTab = false;
            this.txtRegUserName.AnimationSpeed = 200;
            this.txtRegUserName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRegUserName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRegUserName.BackColor = System.Drawing.Color.Transparent;
            this.txtRegUserName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRegUserName.BackgroundImage")));
            this.txtRegUserName.BorderColorActive = System.Drawing.Color.White;
            this.txtRegUserName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRegUserName.BorderColorHover = System.Drawing.Color.White;
            this.txtRegUserName.BorderColorIdle = System.Drawing.Color.DarkSlateGray;
            this.txtRegUserName.BorderRadius = 4;
            this.txtRegUserName.BorderThickness = 2;
            this.txtRegUserName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRegUserName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegUserName.DefaultFont = new System.Drawing.Font("Segoe UI", 12F);
            this.txtRegUserName.DefaultText = "";
            this.txtRegUserName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.txtRegUserName.ForeColor = System.Drawing.Color.White;
            this.txtRegUserName.HideSelection = true;
            this.txtRegUserName.IconLeft = global::ReadExcelApp.Properties.Resources.user;
            this.txtRegUserName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegUserName.IconPadding = 10;
            this.txtRegUserName.IconRight = null;
            this.txtRegUserName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegUserName.Lines = new string[0];
            this.txtRegUserName.Location = new System.Drawing.Point(17, 20);
            this.txtRegUserName.MaxLength = 32767;
            this.txtRegUserName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRegUserName.Modified = false;
            this.txtRegUserName.Multiline = false;
            this.txtRegUserName.Name = "txtRegUserName";
            stateProperties9.BorderColor = System.Drawing.Color.White;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegUserName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRegUserName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.White;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegUserName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DarkSlateGray;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegUserName.OnIdleState = stateProperties12;
            this.txtRegUserName.Padding = new System.Windows.Forms.Padding(3);
            this.txtRegUserName.PasswordChar = '\0';
            this.txtRegUserName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRegUserName.PlaceholderText = "Enter Name";
            this.txtRegUserName.ReadOnly = false;
            this.txtRegUserName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRegUserName.SelectedText = "";
            this.txtRegUserName.SelectionLength = 0;
            this.txtRegUserName.SelectionStart = 0;
            this.txtRegUserName.ShortcutsEnabled = true;
            this.txtRegUserName.Size = new System.Drawing.Size(249, 50);
            this.txtRegUserName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRegUserName.TabIndex = 1;
            this.txtRegUserName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRegUserName.TextMarginBottom = 0;
            this.txtRegUserName.TextMarginLeft = 3;
            this.txtRegUserName.TextMarginTop = 0;
            this.txtRegUserName.TextPlaceholder = "Enter Name";
            this.txtRegUserName.UseSystemPasswordChar = false;
            this.txtRegUserName.WordWrap = true;
            // 
            // panel1
            // 
            this.panel1.BackgroundImage = global::ReadExcelApp.Properties.Resources.stadistics__1_;
            this.panel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.panel1.Location = new System.Drawing.Point(81, 12);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(143, 105);
            this.panel1.TabIndex = 8;
            // 
            // LoginForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(74)))), ((int)(((byte)(86)))));
            this.ClientSize = new System.Drawing.Size(308, 486);
            this.Controls.Add(this.bcRegisteration);
            this.Controls.Add(this.bcLogin);
            this.Controls.Add(this.lbVersion);
            this.Controls.Add(this.lbExit);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "LoginForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "LoginForm";
            this.Load += new System.EventHandler(this.LoginForm_Load);
            this.bcLogin.ResumeLayout(false);
            this.bcRegisteration.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label lbVersion;
        private Bunifu.Framework.UI.BunifuCards bcLogin;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRegister;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogin;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtUserName;
        private System.Windows.Forms.Label lbExit;
        private Bunifu.Framework.UI.BunifuCards bcRegisteration;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegRePassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLoginForm;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCreateAccount;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegUserName;
    }
}